###
POST http://localhost:8080/spring/kafka/publish
Content-Type: application/json

{
  "messageText": "Message sent over spring"
}

###
POST http://localhost:8080/camel/kafka/publish
Content-Type: application/json

{
  "messageText": "Another message sent over camel route"
}
